import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Yeseva_One } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const plusJakarta = Plus_Jakarta_Sans({ subsets: ["latin"], variable: '--font-jakarta' });
const yesevaOne = Yeseva_One({ subsets: ["latin"], weight: '400', variable: '--font-yeseva' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(plusJakarta.className, yesevaOne.variable)}>{children}</body>
    </html>
  );
}
